title       = "spr"
baseURL     = "https://springer-cli.tamnd.com/"
description = "A delightful command line for link.springer.com"
contentDir  = "content"
outputDir   = "public"
theme       = "tago-doks"
syntaxHighlight = "true"

[params]
github = "https://github.com/tamnd/springer-cli"
